- name: Install Docker on Production Machine
  hosts: prod
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes